apiVersion: v1
kind: Template
metadata:
  name: epam-template
  annotations:
    description: "Template for all resources required to stand up the EPAM"
    tags: "epam"
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"epam:latest","namespace":"dept-gpm"},"fieldPath":"spec.template.spec.containers[?(@.name==\"epam\")].image"}]'
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: epam-scheduler
        app.kubernetes.io/component: epam-scheduler
        app.kubernetes.io/instance: epam-scheduler
      name: epam-scheduler
    spec:
      matchLabels:
        app: epam-queue
      selector:
        matchLabels:
          deployment: epam-scheduler
      strategy: {}
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            deployment: epam-scheduler
        spec:
          containers:
          - env:
            - name: APP_DEBUG
              value: "false"
            - name: APP_ENV
              value: production
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: epam-app
                  key: APP_KEY
            - name: APP_NAME
              value: EPAM
            - name: APP_URL
              value: https://epam-dept-gpm.apps.cloudapps.unc.edu/
            - name: AWS_ACCESS_KEY_ID
            - name: AWS_BUCKET
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_SECRET_ACCESS_KEY
            - name: BROADCAST_DRIVER
              value: log
            - name: CACHE_DRIVER
              value: redis
            - name: CONTAINER_ROLE
              value: ${CONTAINER_ROLE}
            - name: DB_CONNECTION
              value: mysql
            - name: DB_DATABASE
              value: epam
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: epam-mysql
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: epam-mysql
                  key: MYSQL_PASWORD
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: database-password
            - name: LOG_CHANNEL
              value: stack
            - name: LOG_LEVEL
              value: debug
            - name: MAIL_ENCRYPTION
              value: "null"
            - name: MAIL_FROM_ADDRESS
              value: epam@clinicalgenome.org
            - name: MAIL_FROM_NAME
              value: "ClinGen Expert Panel Applications"
            - name: MAIL_HOST
              value: relay.unc.edu
            - name: MAIL_MAILER
              value: log
            - name: MAIL_PASSWORD
              value: "null"
            - name: MAIL_PORT
              value: "25"
            - name: MAIL_USERNAME
              value: "null"
            - name: MEMCACHED_HOST
              value: 127.0.0.1
            - name: MIX_PUSHER_APP_CLUSTER
              value: "null"
            - name: MIX_PUSHER_APP_KEY
              value: "null"
            - name: PUSHER_APP_CLUSTER
              value: mt1
            - name: PUSHER_APP_ID
            - name: PUSHER_APP_KEY
            - name: PUSHER_APP_SECRET
            - name: QUEUE_CONNECTION
              value: redis
            - name: SANCTUM_STATEFUL_DOMAINS
              value: epam-app-jward3.cloudapps.unc.edu
            - name: SESSION_DRIVER
              value: redis
            - name: SESSION_LIFETIME
              value: "120"
            image: image-registry.openshift-image-registry.svc:5000/dept-gpm/epam@sha256:23e10addb95140b6a71197e6293c0f701cc5c28711216508a481d0b1dc483758
            name: epam-scheduler
            ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            resources: {}
    status: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: epam-scheduler
        app.kubernetes.io/component: epam-scheduler
        app.kubernetes.io/instance: epam-scheduler
      name: epam-scheduler
    spec:
      ports:
      - name: 80-tcp
        port: 80
        protocol: TCP
        targetPort: 80
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      - name: 8443-tcp
        port: 8443
        protocol: TCP
        targetPort: 8443
      selector:
        deployment: epam-scheduler
    status:
      loadBalancer: {}
parameters:
  - name: CONTAINER_ROLE
    description: "role for the container.  Determines entrypoint behavior"
    value: app