apiVersion: v1
kind: Template
metadata:
  name: epam-template
  annotations:
    description: "A test template"
    tags: "test,mysql"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: databasesecrets
    type: Opaque
    data:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
parameters:
  # - description: MySql database
  #   from: '[A-Za-z0-9]*'
  #   name: MYSQL_DATABASE
  # - description: Username for mysql
  #   from: '[A-Za-z0-9]*'
  #   name: MYSQL_USER
  - description: Password for MYSQL_USER
    from: '[A-Za-z0-9]{8}'      
    generate: expression
    name: MYSQL_PASSWORD
  - description: Password for mysql root user
    from: '[A-Za-z0-9]{12}'      
    generate: expression
    name: MYSQL_ROOT_PASSWORD
labels:
  template: "test-template"
  role: "database"